model_family: llama2-7b

LoRA:
  r: 32
  alpha: 64
  dropout: 0.05

data_path: locuslab/TOFU
split: full
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
save_dir: paper_models/${model_family}_epochs${num_epochs}_lr${lr}_bs${batch_size}_lora
lr: 1e-4
weight_decay: 0.01
seed: 42
